[package]
name = "tachyon-sql"
description = "Parsing de pipeline.sql (DataFusion SQL + extensiones de streaming)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tachyon-core = { version = "0.1.0", path = "../tachyon-core" }
datafusion.workspace = true
